#! /usr/bin/env python

import roslib; roslib.load_manifest('dynamic_graph_actionlib')
import rospy

import actionlib

import dynamic_graph_actionlib.msg

import sys

def run_commands_client(commands):
    client = actionlib.SimpleActionClient(
        'run_commands',
        dynamic_graph_actionlib.msg.RunDynamicGraphCommandsAction)
    client.wait_for_server()

    goal = dynamic_graph_actionlib.msg.RunDynamicGraphCommandsGoal(commands)
    client.send_goal(goal)
    client.wait_for_result()
    return client.get_result()

if __name__ == '__main__':
    try:
        rospy.init_node('run_commands_client_py')

        if len(sys.argv) != 2:
            print("usage: rosrun dynamic_graph_actionlib" + \
                      " RunCommandsClient <python command>")
            sys.exit(1)

        result = run_commands_client(sys.argv[1])
        print("Result: " + result.result)
        print("stdout: " + result.stdout)
        print("stderr: " + result.stderr)
    except rospy.ROSInterruptException:
        print "program interrupted before completion"
